<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorGenreSeeder extends Seeder
{
    public function run(): void
    {
        $actorGenres = [
            ['name' => 'Liam Neeson', 'genre_ids' =>[28, 80, 53]],
            ['name' => 'Anna-Maria Sieklucka', 'genre_ids' =>[10749, 18]],
            ['name' => 'Dylan Sprouse', 'genre_ids' =>[28, 53]],
            ['name' => 'Scott Eastwood', 'genre_ids' =>[28, 80, 53]],
            ['name' => 'Mikey Madison', 'genre_ids' =>[18, 35, 10749]],
            ['name' => 'Jason Patric', 'genre_ids' =>[28, 80, 53, 18]],
            ['name' => 'Robert Downey Jr.', 'genre_ids' =>[12, 878, 28]],
            ['name' => 'Robert Downey Jr.', 'genre_ids' =>[12, 28, 878]],
            ['name' => 'Will Smith', 'genre_ids' =>[28, 35, 80, 53, 12]],
            ['name' => 'Anthony Mackie', 'genre_ids' =>[878, 28, 53]],
            ['name' => 'Sophie Thatcher', 'genre_ids' =>[878, 27, 35]],
            ['name' => 'Huang Bo', 'genre_ids' =>[28, 14, 10752]],
            ['name' => 'Ryan Reynolds', 'genre_ids' =>[28, 35, 878]],
            ['name' => 'Anthony Mackie', 'genre_ids' =>[28, 878, 53]],
            ['name' => 'Vin Diesel', 'genre_ids' =>[28, 80, 53]],
            ['name' => 'Paul Mescal', 'genre_ids' =>[28, 12, 18]],
            ['name' => 'Rebecca Hall', 'genre_ids' =>[28, 12, 878]],
            ['name' => 'Daniel Radcliffe', 'genre_ids' =>[12, 14]],
            ['name' => 'Chris Pratt', 'genre_ids' =>[12, 28, 878]],
            ['name' => 'Scarlett Johansson', 'genre_ids' =>[878, 12, 53]],
            ['name' => 'Jack Black', 'genre_ids' =>[16, 10751, 14, 28]],
            ['name' => 'Nicole Wallace', 'genre_ids' =>[10749, 18]],
            ['name' => 'Sjur Vatne Brean', 'genre_ids' =>[10752, 36, 18]],
            ['name' => 'Harrison Ford', 'genre_ids' =>[12, 28]],
            ['name' => 'Dwayne Johnson', 'genre_ids' =>[28, 14, 35, 12]],
            ['name' => 'Cody Rhodes', 'genre_ids' =>[28]],
            ['name' => 'Woo Yeol', 'genre_ids' =>[35, 18, 10749]],
            ['name' => 'Taito Ban', 'genre_ids' =>[28, 12, 14, 16]],
            ['name' => 'Ben Schwartz', 'genre_ids' =>[28, 12, 10751, 35]],
            ['name' => 'Jim Carrey', 'genre_ids' =>[28, 878, 35, 10751]],
            ['name' => 'Tom Holland', 'genre_ids' =>[28, 12, 878]],
            ['name' => 'Tim Robbins', 'genre_ids' =>[18, 80]],
            ['name' => 'Lupita Nyongo', 'genre_ids' =>[16, 878, 10751]],
            ['name' => 'Cynthia Erivo', 'genre_ids' =>[18, 10749, 14]],
            ['name' => 'Nicole Wallace', 'genre_ids' =>[10749, 18]],
            ['name' => 'Will Ferrell', 'genre_ids' =>[35]],
            ['name' => 'Nicolas Cage', 'genre_ids' =>[28, 27, 53, 878]],
            ['name' => 'Gabriela Andrada', 'genre_ids' =>[10749, 18]],
            ['name' => 'Samara Weaving', 'genre_ids' =>[28, 27, 53]],
            ['name' => 'Nicole Kidman', 'genre_ids' =>[18]],
            ['name' => 'Cameron Diaz', 'genre_ids' =>[28, 35]],
            ['name' => 'Audrey Avila', 'genre_ids' =>[18]],
            ['name' => 'Taron Egerton', 'genre_ids' =>[53, 28]],
            ['name' => 'Ralph Fiennes', 'genre_ids' =>[18, 9648, 53]],
            ['name' => 'Kappei Yamaguchi', 'genre_ids' =>[16, 35, 28]],
            ['name' => 'Steve Carell', 'genre_ids' =>[16, 10751, 35, 878]],
            ['name' => 'Eva Green', 'genre_ids' =>[28, 18, 53, 10752]],
            ['name' => 'Peter Hastings', 'genre_ids' =>[10751, 16, 35, 28]],
            ['name' => 'Xie Miao', 'genre_ids' =>[28, 18]],
            ['name' => 'Frank Lammers', 'genre_ids' =>[28, 18, 80, 53]],
            ['name' => 'Michelle Dockery', 'genre_ids' =>[53, 28, 80]],
            ['name' => 'Hugh Grant', 'genre_ids' =>[27, 53]],
            ['name' => 'Amy Poehler', 'genre_ids' =>[16, 12, 35, 10751]],
            ['name' => 'Matthew McConaughey', 'genre_ids' =>[12, 18, 878]],
            ['name' => 'Owen Teague', 'genre_ids' =>[878, 12, 28]],
            ['name' => 'Aaron Taylor-Johnson', 'genre_ids' =>[28, 12, 53]],
            ['name' => 'Taskya Namya', 'genre_ids' =>[27, 53]],
            ['name' => 'Sarah Snook', 'genre_ids' =>[16, 18, 35]],
            ['name' => 'Jackie Chan', 'genre_ids' =>[28, 35]],
            ['name' => 'Sofia Kappel', 'genre_ids' =>[18]],
            ['name' => 'Christine Bermas', 'genre_ids' =>[18]],
            ['name' => 'Joseph Millson', 'genre_ids' =>[27, 53]],
            ['name' => 'Siena Agudong', 'genre_ids' =>[35, 10749]],
            ['name' => 'Wim van Damme', 'genre_ids' =>[10749]],
            ['name' => 'Naomi Scott', 'genre_ids' =>[27, 9648]],
            ['name' => 'Lauren LaVera', 'genre_ids' =>[27, 53]],
            ['name' => 'William Moseley', 'genre_ids' =>[28]],
            ['name' => 'William Moseley', 'genre_ids' =>[12, 10751, 14]],
            ['name' => 'Tomer Sisley', 'genre_ids' =>[28, 12, 53]],
            ['name' => 'Demi Moore', 'genre_ids' =>[27, 878]],
            ['name' => 'Chris Hemsworth', 'genre_ids' =>[16, 878, 12, 10751]],
            ['name' => 'Tom Hardy', 'genre_ids' =>[28, 878, 12]],
            ['name' => 'Ben Whitehead', 'genre_ids' =>[16, 35, 10751, 12]],
            ['name' => 'Frank Grillo', 'genre_ids' =>[28, 27, 53]],
            ['name' => 'Christopher Abbott', 'genre_ids' =>[27, 53]],
            ['name' => 'Vin Diesel', 'genre_ids' =>[28, 12, 53, 80]],
            ['name' => ' Ron Perlman', 'genre_ids' =>[28, 80, 53]],
            ['name' => ' Michele Morrone', 'genre_ids' =>[10749, 18]],
            ['name' => ' Mason Gooding', 'genre_ids' =>[28, 53]],
            ['name' => ' Sylvester Stallone', 'genre_ids' =>[28, 80, 53]],
            ['name' => ' Mark Eydelshteyn', 'genre_ids' =>[18, 35, 10749]],
            ['name' => ' Sylvester Stallone', 'genre_ids' =>[28, 80, 53, 18]],
            ['name' => ' Chris Evans', 'genre_ids' =>[12, 878, 28]],
            ['name' => ' Chris Evans', 'genre_ids' =>[12, 28, 878]],
            ['name' => ' Martin Lawrence', 'genre_ids' =>[28, 35, 80, 53, 12]],
            ['name' => ' Danny Ramirez', 'genre_ids' =>[878, 28, 53]],
            ['name' => ' Jack Quaid', 'genre_ids' =>[878, 27, 35]],
            ['name' => ' Yu Shi', 'genre_ids' =>[28, 14, 10752]],
            ['name' => ' Hugh Jackman', 'genre_ids' =>[28, 35, 878]],
            ['name' => ' Morena Baccarin', 'genre_ids' =>[28, 878, 53]],
            ['name' => ' Michelle Rodriguez', 'genre_ids' =>[28, 80, 53]],
            ['name' => ' Denzel Washington', 'genre_ids' =>[28, 12, 18]],
            ['name' => ' Brian Tyree Henry', 'genre_ids' =>[28, 12, 878]],
            ['name' => ' Rupert Grint', 'genre_ids' =>[12, 14]],
            ['name' => ' Bryce Dallas Howard', 'genre_ids' =>[12, 28, 878]],
            ['name' => ' Jonathan Bailey', 'genre_ids' =>[878, 12, 53]],
            ['name' => ' Awkwafina', 'genre_ids' =>[16, 10751, 14, 28]],
            ['name' => ' Gabriel Guevara', 'genre_ids' =>[10749, 18]],
            ['name' => ' Erik Hivju', 'genre_ids' =>[10752, 36, 18]],
            ['name' => ' Karen Allen', 'genre_ids' =>[12, 28]],
            ['name' => ' Chris Evans', 'genre_ids' =>[28, 14, 35, 12]],
            ['name' => ' Kevin Steen', 'genre_ids' =>[28]],
            ['name' => ' So Jeong', 'genre_ids' =>[35, 18, 10749]],
            ['name' => ' Genta Nakamura', 'genre_ids' =>[28, 12, 14, 16]],
            ['name' => ' James Marsden', 'genre_ids' =>[28, 12, 10751, 35]],
            ['name' => ' Ben Schwartz', 'genre_ids' =>[28, 878, 35, 10751]],
            ['name' => ' Zendaya', 'genre_ids' =>[28, 12, 878]],
            ['name' => ' Morgan Freeman', 'genre_ids' =>[18, 80]],
            ['name' => ' Pedro Pascal', 'genre_ids' =>[16, 878, 10751]],
            ['name' => ' Ariana Grande', 'genre_ids' =>[18, 10749, 14]],
            ['name' => ' Gabriel Guevara', 'genre_ids' =>[10749, 18]],
            ['name' => ' Reese Witherspoon', 'genre_ids' =>[35]],
            ['name' => ' Jaeden Martell', 'genre_ids' =>[28, 27, 53, 878]],
            ['name' => ' Mario Ermito', 'genre_ids' =>[10749, 18]],
            ['name' => ' Vic Carmen Sonne', 'genre_ids' =>[28, 27, 53]],
            ['name' => ' Harris Dickinson', 'genre_ids' =>[18]],
            ['name' => ' Jamie Foxx', 'genre_ids' =>[28, 35]],
            ['name' => ' Dani Yoshida', 'genre_ids' =>[18]],
            ['name' => ' Jason Bateman', 'genre_ids' =>[53, 28]],
            ['name' => ' Stanley Tucci', 'genre_ids' =>[18, 9648, 53]],
            ['name' => ' Hideyuki Tanaka', 'genre_ids' =>[16, 35, 28]],
            ['name' => ' Kristen Wiig', 'genre_ids' =>[16, 10751, 35, 878]],
            ['name' => ' Maria Bakalova', 'genre_ids' =>[28, 18, 53, 10752]],
            ['name' => ' Pete Davidson', 'genre_ids' =>[10751, 16, 35, 28]],
            ['name' => ' Yang Enyou', 'genre_ids' =>[28, 18]],
            ['name' => ' Aiko Beemsterboer', 'genre_ids' =>[28, 18, 80, 53]],
            ['name' => ' Mark Wahlberg', 'genre_ids' =>[53, 28, 80]],
            ['name' => ' Sophie Thatcher', 'genre_ids' =>[27, 53]],
            ['name' => ' Maya Hawke', 'genre_ids' =>[16, 12, 35, 10751]],
            ['name' => ' Anne Hathaway', 'genre_ids' =>[12, 18, 878]],
            ['name' => ' Freya Allan', 'genre_ids' =>[878, 12, 28]],
            ['name' => ' Ariana DeBose', 'genre_ids' =>[28, 12, 53]],
            ['name' => ' Yasamin Jasem', 'genre_ids' =>[27, 53]],
            ['name' => ' Kodi Smit-McPhee', 'genre_ids' =>[16, 18, 35]],
            ['name' => ' Shi Ce', 'genre_ids' =>[28, 35]],
            ['name' => ' Zelda Morrison', 'genre_ids' =>[18]],
            ['name' => ' Gold Aceron', 'genre_ids' =>[18]],
            ['name' => ' Sarah Alexandra Marks', 'genre_ids' =>[27, 53]],
            ['name' => ' Noah Beck', 'genre_ids' =>[35, 10749]],
            ['name' => ' Floor Wyns', 'genre_ids' =>[10749]],
            ['name' => ' Rosemarie DeWitt', 'genre_ids' =>[27, 9648]],
            ['name' => ' David Howard Thornton', 'genre_ids' =>[27, 53]],
            ['name' => ' Colm Meaney', 'genre_ids' =>[28]],
            ['name' => ' Anna Popplewell', 'genre_ids' =>[12, 10751, 14]],
            ['name' => ' James Franco', 'genre_ids' =>[28, 12, 53]],
            ['name' => ' Margaret Qualley', 'genre_ids' =>[27, 878]],
            ['name' => ' Brian Tyree Henry', 'genre_ids' =>[16, 878, 12, 10751]],
            ['name' => ' Chiwetel Ejiofor', 'genre_ids' =>[28, 878, 12]],
            ['name' => ' Peter Kay', 'genre_ids' =>[16, 35, 10751, 12]],
            ['name' => ' Katrina Law', 'genre_ids' =>[28, 27, 53]],
            ['name' => ' Julia Garner', 'genre_ids' =>[27, 53]],
            ['name' => ' Asia Argento', 'genre_ids' =>[28, 12, 53, 80]],
            ['name' => ' Yolonda Ross', 'genre_ids' =>[28, 80, 53]],
            ['name' => ' Simone Susinna', 'genre_ids' =>[10749, 18]],
            ['name' => ' Dichen Lachman', 'genre_ids' =>[28, 53]],
            ['name' => ' Willa Fitzgerald', 'genre_ids' =>[28, 80, 53]],
            ['name' => ' Yura Borisov', 'genre_ids' =>[18, 35, 10749]],
            ['name' => ' Josh Wiggins', 'genre_ids' =>[28, 80, 53, 18]],
            ['name' => ' Mark Ruffalo', 'genre_ids' =>[12, 878, 28]],
            ['name' => ' Chris Hemsworth', 'genre_ids' =>[12, 28, 878]],
            ['name' => ' Vanessa Hudgens', 'genre_ids' =>[28, 35, 80, 53, 12]],
            ['name' => ' Harrison Ford', 'genre_ids' =>[878, 28, 53]],
            ['name' => ' Lukas Gage', 'genre_ids' =>[878, 27, 35]],
            ['name' => ' Nashi', 'genre_ids' =>[28, 14, 10752]],
            ['name' => ' Emma Corrin', 'genre_ids' =>[28, 35, 878]],
            ['name' => ' Maddie Hasson', 'genre_ids' =>[28, 878, 53]],
            ['name' => ' Tyrese Gibson', 'genre_ids' =>[28, 80, 53]],
            ['name' => ' Pedro Pascal', 'genre_ids' =>[28, 12, 18]],
            ['name' => ' Dan Stevens', 'genre_ids' =>[28, 12, 878]],
            ['name' => ' Emma Watson', 'genre_ids' =>[12, 14]],
            ['name' => ' Laura Dern', 'genre_ids' =>[12, 28, 878]],
            ['name' => ' Mahershala Ali', 'genre_ids' =>[878, 12, 53]],
            ['name' => ' Viola Davis', 'genre_ids' =>[16, 10751, 14, 28]],
            ['name' => ' Marta Hazas', 'genre_ids' =>[10749, 18]],
            ['name' => ' Philip Helgar', 'genre_ids' =>[10752, 36, 18]],
            ['name' => ' Paul Freeman', 'genre_ids' =>[12, 28]],
            ['name' => ' Lucy Liu', 'genre_ids' =>[28, 14, 35, 12]],
            ['name' => ' Chelsea Cardona', 'genre_ids' =>[28]],
            ['name' => ' Lee Chae-dam', 'genre_ids' =>[35, 18, 10749]],
            ['name' => ' Haruna Mikawa', 'genre_ids' =>[28, 12, 14, 16]],
            ['name' => ' Tika Sumpter', 'genre_ids' =>[28, 12, 10751, 35]],
            ['name' => ' Keanu Reeves', 'genre_ids' =>[28, 878, 35, 10751]],
            ['name' => ' Benedict Cumberbatch', 'genre_ids' =>[28, 12, 878]],
            ['name' => ' Bob Gunton', 'genre_ids' =>[18, 80]],
            ['name' => ' Kit Connor', 'genre_ids' =>[16, 878, 10751]],
            ['name' => ' Jeff Goldblum', 'genre_ids' =>[18, 10749, 14]],
            ['name' => ' Marta Hazas', 'genre_ids' =>[10749, 18]],
            ['name' => ' Geraldine Viswanathan', 'genre_ids' =>[35]],
            ['name' => ' Maxwell Jenkins', 'genre_ids' =>[28, 27, 53, 878]],
            ['name' => ' Celia Freijeiro', 'genre_ids' =>[10749, 18]],
            ['name' => ' Katariina Unt', 'genre_ids' =>[28, 27, 53]],
            ['name' => ' Antonio Banderas', 'genre_ids' =>[18]],
            ['name' => ' McKenna Roberts', 'genre_ids' =>[28, 35]],
            ['name' => ' Denise Esteban', 'genre_ids' =>[18]],
            ['name' => ' Sofia Carson', 'genre_ids' =>[53, 28]],
            ['name' => ' John Lithgow', 'genre_ids' =>[18, 9648, 53]],
            ['name' => ' Reiko Oimori', 'genre_ids' =>[16, 35, 28]],
            ['name' => ' Will Ferrell', 'genre_ids' =>[16, 10751, 35, 878]],
            ['name' => ' Ruby Rose', 'genre_ids' =>[28, 18, 53, 10752]],
            ['name' => ' Lil Rel Howery', 'genre_ids' =>[10751, 16, 35, 28]],
            ['name' => ' Huang Tao', 'genre_ids' =>[28, 18]],
            ['name' => ' Tobias Kersloot', 'genre_ids' =>[28, 18, 80, 53]],
            ['name' => ' Topher Grace', 'genre_ids' =>[53, 28, 80]],
            ['name' => ' Chloe East', 'genre_ids' =>[27, 53]],
            ['name' => ' Kensington Tallman', 'genre_ids' =>[16, 12, 35, 10751]],
            ['name' => ' Michael Caine', 'genre_ids' =>[12, 18, 878]],
            ['name' => ' Kevin Durand', 'genre_ids' =>[878, 12, 28]],
            ['name' => ' Fred Hechinger', 'genre_ids' =>[28, 12, 53]],
            ['name' => ' Arya Saloka', 'genre_ids' =>[27, 53]],
            ['name' => ' Jacki Weaver', 'genre_ids' =>[16, 18, 35]],
            ['name' => ' Wei Xiang', 'genre_ids' =>[28, 35]],
            ['name' => ' Tee Reel', 'genre_ids' =>[18]],
            ['name' => ' VR Relosa', 'genre_ids' =>[18]],
            ['name' => ' David Wayman', 'genre_ids' =>[27, 53]],
            ['name' => ' Drew Ray Tanner', 'genre_ids' =>[35, 10749]],
            ['name' => ' Lukas Gage', 'genre_ids' =>[27, 9648]],
            ['name' => ' Samantha Scaffidi', 'genre_ids' =>[27, 53]],
            ['name' => ' Jesse Hutch', 'genre_ids' =>[28]],
            ['name' => ' Skandar Keynes', 'genre_ids' =>[12, 10751, 14]],
            ['name' => ' Clotilde Hesme', 'genre_ids' =>[28, 12, 53]],
            ['name' => ' Dennis Quaid', 'genre_ids' =>[27, 878]],
            ['name' => ' Scarlett Johansson', 'genre_ids' =>[16, 878, 12, 10751]],
            ['name' => ' Juno Temple', 'genre_ids' =>[28, 878, 12]],
            ['name' => ' Lauren Patel', 'genre_ids' =>[16, 35, 10751, 12]],
            ['name' => ' Ilfenesh Hadera', 'genre_ids' =>[28, 27, 53]],
            ['name' => ' Matilda Firth', 'genre_ids' =>[27, 53]],
            ['name' => ' Marton Csokas', 'genre_ids' =>[28, 12, 53, 80]],
        ];

        foreach ($actorGenres as $entry) {
            $actor = DB::table('actor')->where('name', $entry['name'])->first();

            if ($actor) {
                $actor_id = $actor->actor_id;

                foreach ($entry['genre_ids'] as $genre_id) {
                    // Check if the entry already exists to prevent duplicates
                    $exists = DB::table('actor_genre')
                        ->where('actor_id', $actor_id)
                        ->where('genre_id', $genre_id)
                        ->exists();

                    if (!$exists) {
                        DB::table('actor_genre')->insert([
                            'actor_id' => $actor_id,
                            'genre_id' => $genre_id,
                        ]);
                    }
                }
            }
        }
    }
}