<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorSeeder extends Seeder
{
    public function run(): void
    {
        $actors = [
            ['name' => 'Liam Neeson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Anna-Maria Sieklucka', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Dylan Sprouse', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Scott Eastwood', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mikey Madison', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jason Patric', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Robert Downey Jr.', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Will Smith', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Anthony Mackie', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sophie Thatcher', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Huang Bo', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ryan Reynolds', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Vin Diesel', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Paul Mescal', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Rebecca Hall', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Daniel Radcliffe', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chris Pratt', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Scarlett Johansson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jack Black', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Nicole Wallace', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sjur Vatne Brean', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Harrison Ford', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Dwayne Johnson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Cody Rhodes', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Woo Yeol', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Taito Ban', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ben Schwartz', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jim Carrey', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tom Holland', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tim Robbins', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lupita Nyong', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Cynthia Erivo', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Will Ferrell', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Nicolas Cage', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Gabriela Andrada', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Samara Weaving', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Nicole Kidman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Cameron Diaz', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Audrey Avila', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Taron Egerton', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ralph Fiennes', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kappei Yamaguchi', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Steve Carell', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Eva Green', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Peter Hastings', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Xie Miao', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Frank Lammers', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Michelle Dockery', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Hugh Grant', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Amy Poehler', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Matthew McConaughey', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Owen Teague', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Aaron Taylor-Johnson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Taskya Namya', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sarah Snook', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jackie Chan', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sofia Kappel', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Christine Bermas', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Joseph Millson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Siena Agudong', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Wim van Damme', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Naomi Scott', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lauren LaVera', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'William Moseley', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tomer Sisley', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Demi Moore', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chris Hemsworth', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tom Hardy', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ben Whitehead', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Frank Grillo', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Christopher Abbott', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ron Perlman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Michele Morrone', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mason Gooding', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sylvester Stallone', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mark Eydelshteyn', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chris Evans', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Martin Lawrence', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Danny Ramirez', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jack Quaid', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Yu Shi', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Hugh Jackman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Morena Baccarin', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Michelle Rodriguez', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Denzel Washington', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Brian Tyree Henry', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Rupert Grint', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Bryce Dallas Howard', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jonathan Bailey', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Awkwafina', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Gabriel Guevara', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Erik Hivju', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Karen Allen', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kevin Steen', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'So Jeong', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Genta Nakamura', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'James Marsden', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ben Schwartz', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Zendaya', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Morgan Freeman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Pedro Pascal', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ariana Grande', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Reese Witherspoon', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jaeden Martell', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mario Ermito', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Vic Carmen Sonne', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Harris Dickinson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jamie Foxx', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Dani Yoshida', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jason Bateman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Stanley Tucci', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Hideyuki Tanaka', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kristen Wiig', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Maria Bakalova', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Pete Davidson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Yang Enyou', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Aiko Beemsterboer', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mark Wahlberg', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sophie Thatcher', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Maya Hawke', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Anne Hathaway', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Freya Allan', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ariana DeBose', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Yasamin Jasem', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kodi Smit-McPhee', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Shi Ce', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Zelda Morrison', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Gold Aceron', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sarah Alexandra Marks', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Noah Beck', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Floor Wyns', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Rosemarie DeWitt', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'David Howard Thornton', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Colm Meaney', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Anna Popplewell', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'James Franco', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Margaret Qualley', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chiwetel Ejiofor', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Peter Kay', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Katrina Law', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Julia Garner', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Asia Argento', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Yolonda Ross', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Simone Susinna', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Dichen Lachman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Willa Fitzgerald', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Yura Borisov', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Josh Wiggins', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mark Ruffalo', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chris Hemsworth', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Vanessa Hudgens', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Harrison Ford', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lukas Gage', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Nashi', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Emma Corrin', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Maddie Hasson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tyrese Gibson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Dan Stevens', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Emma Watson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Laura Dern', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Mahershala Ali', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Viola Davis', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Marta Hazas', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Philip Helgar', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Paul Freeman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lucy Liu', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chelsea Cardona', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lee Chae-dam', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Haruna Mikawa', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tika Sumpter', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Keanu Reeves', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Benedict Cumberbatch', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Bob Gunton', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kit Connor', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jeff Goldblum', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Geraldine Viswanathan', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Maxwell Jenkins', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Celia Freijeiro', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Katariina Unt', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Antonio Banderas', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'McKenna Roberts', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Denise Esteban', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Sofia Carson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'John Lithgow', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Reiko Oimori', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Will Ferrell', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ruby Rose', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lil Rel Howery', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Huang Tao', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tobias Kersloot', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Topher Grace', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Chloe East', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kensington Tallman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Michael Caine', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Kevin Durand', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Fred Hechinger', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Arya Saloka', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jacki Weaver', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Wei Xiang', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Tee Reel', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'VR Relosa', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'David Wayman', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Drew Ray Tanner', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Samantha Scaffidi', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Jesse Hutch', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Skandar Keynes', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Clotilde Hesme', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Dennis Quaid', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Scarlett Johansson', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Juno Temple', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Lauren Patel', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Ilfenesh Hadera', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Matilda Firth', 'headshot_file_path' => 'uploads/Actor.png'],
            ['name' => 'Marton Csokas', 'headshot_file_path' => 'uploads/Actor.png'],
        ];

        DB::table('actor')->insert($actors);
    }
}
